# roles/webserver/tasks/main.yml
---
- name: #1. install Apache
  apt: name=apache2 state=present

- name: #2. install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present

- name: #3. start Apache
  service: name=apache2 state=running enabled=yes

- name: #4. install Hello World PHP script
  copy: src=index.php dest=/var/www/index.php mode=0664

